services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
      - TUNNEL_TRANSPORT_PROTOCOL=${CF_PROTOCOL:-http2}
    command: tunnel --no-autoupdate run
    network_mode: host