services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
      - TUNNEL_TRANSPORT_PROTOCOL=http2  # Чтобы не было проблем с UDP/Buffer size
    command: tunnel run
    networks:
      - cloudweb

networks:
  cloudweb:
    external: true